# Generated by Django 2.2.1 on 2019-05-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tags',
            new_name='tag',
        ),
    ]
