# Generated by Django 2.2.1 on 2019-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190524_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/images/NoProfile.jpg', null=True, upload_to='images/'),
        ),
    ]
